### ISSUE TITLE
External monitor disconnect corrupts ~/.postage/main-window-state.json

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#310]
Steps to reproduce(not yet confirmed):

Users moves Postage app window to external monitor
closes Postage
disconnect external monitor
restart Postage 
will display error:

<img width="421" alt="screen shot 2017-06-13 at 7 56 56 am" src="https://user-images.githubusercontent.com/14250339/27105087-df6a7ca2-5053-11e7-93a9-365cd303b67e.png">

We may want to figure out a way to catch this error or maybe file a bug with Electron. Assigning this to Nunzio, he can figure it out when he gets back second week of June.

### WORKAROUND:

Delete the file. 

On mac: /Users/user name/.postage/main-window-state.json
On windows: c:\Users\user name\.postage\main-window-state.json
On *nix: ~/.postage/main-window-state.json

**Comment by justintocci** [comment]
For searchers, the text of the error is: 

 Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at validateState (/Applications/Postage.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:46:34)
    at module.exports (/Applications/Postage.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:154:3)
    at App.appStart (/Applications/Postage.app/Contents/Resources/app.asar/main.js:475:20)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

**Comment by nunziotocci** [comment]
Unable to reproduce on Windows 10 and macOS Sierra 10.12.5. It's possible Electron fixed this.
